# https://classnotes-api.azurewebsites.net/
name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "ClassNotes.Api/**"
      - ".github/workflows/backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore ClassNotes.Api/ClassNotes.Api.csproj

      - name: Build API
        run: dotnet build ClassNotes.Api/ClassNotes.Api.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ClassNotes.Api/ClassNotes.Api.csproj -c Release --no-build -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ClassNotesEno"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E5F936A3252A48D1893F1CE13FCBDE2B }}
          package: ./publish